apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cm-testpod
  name: cm-testpod
spec:
  containers:
  - image: alpine
    name: cm-testpod
    command: ['bin/sh', '-c', 'echo $(ENV1) - ${ENV1}; echo "--"; echo "env:"; printenv']
    env:
    # Define the environment variable
    - name: ENV1
      valueFrom:
        configMapKeyRef:
          # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
          name: test1
          # Specify the key associated with the value
          key: key1
