apiVersion: v1
kind: Pod
metadata:
  labels:
    run: test-multi-containers
  name: test-multi-containers
spec:
  initContainers:
  - image: alpine
    name: init1
    command: ['/bin/sh', '-c', 'echo -n $(hostname)/init1: sleeping 5 secs ...; sleep 5; echo done']
  - image: alpine
    name: init2
    command: ['/bin/sh', '-c', 'echo -n $(hostname)/init2: sleeping 5 secs ...; sleep 5; echo done']

  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: vol
      mountPath: /usr/share/nginx/html
      #mountPath: /var/lib/nginx/html

  - image: alpine
    name: content
    command: ['/bin/sh', '-c', 'while true; do echo "$(hostname)/content: $(date): o/p from sidecar container" >> /mnt/vol/index.html; sleep 5; done']
    volumeMounts:
    - name: vol
      mountPath: /mnt/vol

  volumes:
  - name: vol
    emptyDir: {}

