apiVersion: v1
kind: Service
metadata:
  labels:
    app: sset
  name: sset-headless-cip
spec:
  type: ClusterIP
  clusterIP: None # ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ckad-demo-sset
